### ISSUE TITLE
mmjstool requires cloning mattermost-mobile for mattermost-webapp

### ISSUE THREAD

**Issue by Willyfrog** [mattermost/mattermost-utilities#5]
When a webapp dev tries to use `make i18n-extract`, it fails due to mmjstool requiring cloning mattermost-mobile.

```
Error: ENOENT: no such file or directory, open '../mattermost-mobile/assets/base/i18n/en.json'
    at Object.openSync (fs.js:448:3)
    at Object.readFileSync (fs.js:348:35)
    at getCurrentTranslations ([...]/mattermost/mattermost-webapp/node_modules/mmjstool/bin/mmjstool:43634:46)
```

Cloning the mobile project in the expected location prevents this from happening.

It shouldn't require any of both repos, or should at least be ignorable so `make i18n-extract` wouldn't fail for a single repo.

I'm not sure I should report it here, let me know if I should open this elsewhere

**Comment by jespino** [comment]
Is ok to report it here, yes, I think can be safe to ignore mattermost-mobile if it is not in place. Thanks for the feedback.
